CREATE TABLE SHIPWRECK(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    CONDITION VARCHAR(255) NOT NULL,
    DEPTH INT NOT NULL,
    LATITUDE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL,
    YEAR_DISCOVERED INT NOT NULL,
);

